name: postgres-stack
services:
  db:
    image: pguam:18.4
    container_name: uamdb
    ports:
      - "${PG_PORT}:5432"
    environment:
      # postgresql://uam_user:uam_password@127.0.0.1:3081/uam_db
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./create_extension.sql:/docker-entrypoint-initdb.d/0-create_extension.sql
      - ./create_pgcron.sh:/docker-entrypoint-initdb.d/1-create_pgcron.sh
      - ./schema.sql:/docker-entrypoint-initdb.d/2-schema.sql
